import dynamics_disordered_systems_random_ising_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dynamics_disordered_systems_random_ising_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dynamics_disordered_systems_random_ising_theorem_canonical_lane_mathlib
end HautevilleHouse
